// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyERP.Services.Production.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyERP.Services.Production.Migrations
{
    [DbContext(typeof(ProductionDbContext))]
    partial class ProductionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyERP.Services.Production.Models.BOM", b =>
                {
                    b.Property<Guid>("BOMId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BomCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("BOMId");

                    b.HasIndex("BomCode")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId", "Version")
                        .IsUnique();

                    b.ToTable("BOMs");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.BOMLine", b =>
                {
                    b.Property<Guid>("BOMLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BOMId")
                        .HasColumnType("uuid");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessName")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RawMaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ScrapPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BOMLineId");

                    b.HasIndex("BOMId");

                    b.HasIndex("ProcessId");

                    b.ToTable("BOMLines");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.Equipment", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostPerHour")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipmentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uuid");

                    b.HasKey("EquipmentId");

                    b.HasIndex("EquipmentCode")
                        .IsUnique();

                    b.HasIndex("WorkCenterId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.EquipmentProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.HasIndex("EquipmentId", "ProcessId")
                        .IsUnique();

                    b.ToTable("EquipmentProcesses");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.MaterialRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityConsumed")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityRequired")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityReserved")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RawMaterialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("MaterialRequirements");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.PendingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProcessedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SalesOrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("SalesOrderId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("PendingRequests");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.PendingRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PendingRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("PendingRequestId");

                    b.ToTable("PendingRequestItems");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.Process", b =>
                {
                    b.Property<Guid>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StandardTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProcessId");

                    b.HasIndex("Category");

                    b.HasIndex("ProcessCode")
                        .IsUnique();

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.ProcessRoute", b =>
                {
                    b.Property<Guid>("ProcessRouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("RouteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uuid");

                    b.HasKey("ProcessRouteId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RouteCode")
                        .IsUnique();

                    b.HasIndex("WorkCenterId");

                    b.ToTable("ProcessRoutes");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.ProcessRouteStep", b =>
                {
                    b.Property<Guid>("ProcessRouteStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("OutputMultiplier")
                        .HasColumnType("numeric");

                    b.Property<string>("OutputUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcessRouteId")
                        .HasColumnType("uuid");

                    b.Property<int>("RunTimePerUnitMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("SetupTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.HasKey("ProcessRouteStepId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("ProcessRouteId");

                    b.ToTable("ProcessRouteSteps");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.ProcessRouteStepMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BOMLineId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessRouteStepId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RawMaterialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BOMLineId");

                    b.HasIndex("ProcessRouteStepId");

                    b.ToTable("ProcessRouteStepMaterials");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.ProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BOMId")
                        .HasColumnType("uuid");

                    b.Property<string>("BomCode")
                        .HasColumnType("text");

                    b.Property<int?>("BomVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastReservationAttempt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MaterialsReturned")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PlannedEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuantityGood")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityPlanned")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityScrap")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReleasedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("ReservationAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("ReservationFailReason")
                        .HasColumnType("text");

                    b.Property<string>("ReservationStatus")
                        .HasColumnType("text");

                    b.Property<Guid?>("SalesOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SalesOrderNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkCenterId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkCenterName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BOMId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ReservationStatus");

                    b.HasIndex("SalesOrderId");

                    b.HasIndex("Status");

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.WorkCenter", b =>
                {
                    b.Property<Guid>("WorkCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CapacityPerHour")
                        .HasColumnType("integer");

                    b.Property<string>("CenterCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CostPerHour")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkCenterId");

                    b.HasIndex("CenterCode")
                        .IsUnique();

                    b.ToTable("WorkCenters");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.WorkOrder", b =>
                {
                    b.Property<Guid>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProcessRouteStepId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityCompleted")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityPlanned")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityScrap")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("ReservationAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("ReservationFailReason")
                        .HasColumnType("text");

                    b.Property<string>("ReservationStatus")
                        .HasColumnType("text");

                    b.Property<string>("RouteCode")
                        .HasColumnType("text");

                    b.Property<int?>("RouteVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StartedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkCenterId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("ProcessRouteStepId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkCenterId");

                    b.HasIndex("WorkOrderNumber")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.WorkOrderExecution", b =>
                {
                    b.Property<Guid>("ExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActivatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("QuantityProduced")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityScrap")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("ExecutionId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderExecutions");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.BOMLine", b =>
                {
                    b.HasOne("MyERP.Services.Production.Models.BOM", "BOM")
                        .WithMany("Lines")
                        .HasForeignKey("BOMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyERP.Services.Production.Models.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BOM");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.Equipment", b =>
                {
                    b.HasOne("MyERP.Services.Production.Models.WorkCenter", "WorkCenter")
                        .WithMany("Equipment")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.EquipmentProcess", b =>
                {
                    b.HasOne("MyERP.Services.Production.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyERP.Services.Production.Models.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.MaterialRequirement", b =>
                {
                    b.HasOne("MyERP.Services.Production.Models.ProductionOrder", "ProductionOrder")
                        .WithMany("MaterialRequirements")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.PendingRequestItem", b =>
                {
                    b.HasOne("MyERP.Services.Production.Models.PendingRequest", "PendingRequest")
                        .WithMany("Items")
                        .HasForeignKey("PendingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PendingRequest");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.ProcessRoute", b =>
                {
                    b.HasOne("MyERP.Services.Production.Models.WorkCenter", "WorkCenter")
                        .WithMany("ProcessRoutes")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.ProcessRouteStep", b =>
                {
                    b.HasOne("MyERP.Services.Production.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId");

                    b.HasOne("MyERP.Services.Production.Models.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyERP.Services.Production.Models.ProcessRoute", "ProcessRoute")
                        .WithMany("Steps")
                        .HasForeignKey("ProcessRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Process");

                    b.Navigation("ProcessRoute");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.ProcessRouteStepMaterial", b =>
                {
                    b.HasOne("MyERP.Services.Production.Models.BOMLine", "BOMLine")
                        .WithMany()
                        .HasForeignKey("BOMLineId");

                    b.HasOne("MyERP.Services.Production.Models.ProcessRouteStep", "ProcessRouteStep")
                        .WithMany("Materials")
                        .HasForeignKey("ProcessRouteStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BOMLine");

                    b.Navigation("ProcessRouteStep");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.ProductionOrder", b =>
                {
                    b.HasOne("MyERP.Services.Production.Models.BOM", "BOM")
                        .WithMany()
                        .HasForeignKey("BOMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BOM");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.WorkOrder", b =>
                {
                    b.HasOne("MyERP.Services.Production.Models.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId");

                    b.HasOne("MyERP.Services.Production.Models.ProcessRouteStep", "ProcessRouteStep")
                        .WithMany()
                        .HasForeignKey("ProcessRouteStepId");

                    b.HasOne("MyERP.Services.Production.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyERP.Services.Production.Models.WorkCenter", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("WorkCenterId");

                    b.Navigation("Process");

                    b.Navigation("ProcessRouteStep");

                    b.Navigation("ProductionOrder");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.WorkOrderExecution", b =>
                {
                    b.HasOne("MyERP.Services.Production.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyERP.Services.Production.Models.WorkOrder", "WorkOrder")
                        .WithMany("Executions")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.BOM", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.PendingRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.ProcessRoute", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.ProcessRouteStep", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.ProductionOrder", b =>
                {
                    b.Navigation("MaterialRequirements");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.WorkCenter", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("ProcessRoutes");
                });

            modelBuilder.Entity("MyERP.Services.Production.Models.WorkOrder", b =>
                {
                    b.Navigation("Executions");
                });
#pragma warning restore 612, 618
        }
    }
}
